#!/bin/sh
set -e

DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-4000}
DB_NAME=${DB_NAME:-wildman_db}
DB_USER=${DB_USER:-postgres}
DB_PASSWORD=${DB_PASSWORD:-postgre123}
REDIS_HOST=${REDIS_HOST:-localhost}
REDIS_PORT=${REDIS_PORT:-6379}

SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-$DB_USER}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-$DB_PASSWORD}

export SPRING_DATASOURCE_URL
export SPRING_DATASOURCE_USERNAME
export SPRING_DATASOURCE_PASSWORD
export SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST:-$REDIS_HOST}
export SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT:-$REDIS_PORT}

PGPASSWORD="$DB_PASSWORD" psql \
  -h "$DB_HOST" \
  -p "$DB_PORT" \
  -U "$DB_USER" \
  -d "$DB_NAME" \
  -f /app/gpt.sql

exec java -jar /app/app.jar
